### ISSUE TITLE
Table Alias

### ISSUE THREAD

**Issue by ahuhn14** [bluemarblepayroll/sqlstyle.guide#1]
Alias should be the abbreviation of the table name

**Example:** 
lkp_food = lf
lkp_drinks = ld
menu_items = mi

**If there are two tables with the same alias, then do below:** 

menu_items_brunch = mi_brunch
menu_items_beverages = mi_beverages

**Comment by mattruggio** [comment]
### Notes for temporary tables

For temp tables creation, prefix with: `temp_`

Example:

* `temp_cookies` 

Then alias without dropping the prefix: `temp_c`

**Comment by gerryster** [comment]
Addressed in a PR.
