### ISSUE TITLE
Alignment and Structure

### ISSUE THREAD

**Issue by BIHxSALKO** [bluemarblepayroll/sqlstyle.guide#3]
The style guide suggests general query alignment and sturcture like below:

```
SELECT a.title, a.release_date, a.recording_date
  FROM albums AS a
 WHERE a.title = 'Charcoal Lane'
    OR a.title = 'The New Danger';
```

I propose....

```
SELECT 
  a.title, 
  a.release_date, 
  a.recording_date
FROM albums AS a
WHERE a.title = 'Charcoal Lane'
  OR a.title = 'The New Danger';
```

We will left align the SQL keywords. For the columns in the select, each are indented 2  spaces and are on there own line.
Subsequent AND/OR clauses are indented 2 spaces after the WHERE line.

**Comment by gerryster** [comment]
This was incorporated in PR #11.
