### ISSUE TITLE
Input Parameters and Local Vars

### ISSUE THREAD

**Issue by BIHxSALKO** [bluemarblepayroll/sqlstyle.guide#4]
Input parameters for a stored procedure are to be prefixed by an underscore character. They are lowercase and use underscores to represent a natural space.

Local vars are to be prefixed by an underscore character and be in ALL CAPS.

```
CREATE PROCEDURE `test`(
  IN
  _lkp_id       INT
)

BEGIN

DECLARE _LKP_DESCRIPTION        VARCHAR(255)
.
.
.

```

**Comment by mattruggio** [comment]
final form:

```
CREATE PROCEDURE `test`(
  IN
  _lkp_id           INT,
  _lkp_id_id2       INT,
  _lkp_id           INT,
  _lkp_id           INT,
  OUT _something_id INT,
  OUT _something_id INT,
  OUT _something_id INT
)

BEGIN

DECLARE _LKP_DESCRIPTION VARCHAR(255);
```

Notes:

* underscore argument names
* align argument types with longest argument name + 1 space
* all in's before outs
* local variables are screaming snake caps with prefixed underscore

**Comment by gerryster** [comment]
This was incorporated in PR #11.
