### ISSUE TITLE
Not Equal To Syntax Consistency

### ISSUE THREAD

**Issue by BIHxSALKO** [bluemarblepayroll/sqlstyle.guide#6]
This is something I noticed from my work with procs. I see instances where not equal to is referred to by <> and some instances of where it is !=.

Should we try to be consistent with the syntax across procs or is this better left as developers choice? I personally like != syntax myself.

```
SELECT
.
.
.
WHERE  column1 <> 0
  OR column2 != 4;
```

**Comment by mattruggio** [comment]
both forms are acceptable, but consistent within same file would be nice.
